### Spring JPA Properties ###
spring:
  datasource:
    url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS MAPBOX
    username: sa
    password: ''
    driverClassName: org.h2.Driver
    hikari:
      max-pool-size: 15
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create

### Application Port and address###
#server:
#  port: ${ELEC_PORT:27000}
#  servlet:
#    session:
#      cookie:
#        name: X-SAP-DI-AAT
#  proxy:
#    enabled: false
#    host: proxy
#    port: 8080
#spring:
#  datasource:
#    url: ${DB_URL}
#    username: ${DB_USER}
#    password: ${DB_PASSWORD}
#    driverClassName: com.sybase.jdbc4.jdbc.SybDriver
#    hikari:
#      max-pool-size: 15
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.SybaseAnywhereDialect
#      org:
#        hibernate:
#          envers:
#            audit_table_suffix: _audit
#            store_data_at_delete: true
#            revision_on_collection_change: false
#
